tinyMCE.addI18n('ja.umbraco',{
"underline_desc":"ä¸‹ç·š (Ctrl+U)",
"italic_desc":"æ–œä½“ (Ctrl+I)",
"bold_desc":"å¤ªå­— (Ctrl+B)",
dd:"èªžå¥ã®èª¬æ˜Ž",
dt:"èªžå¥ã®å®šç¾©",
samp:"ã‚³ãƒ¼ãƒ‰ã®ä¾‹",
code:"ã‚³ãƒ¼ãƒ‰",
blockquote:"å¼•ç”¨",
h6:"è¦‹å‡ºã—6",
h5:"è¦‹å‡ºã—5",
h4:"è¦‹å‡ºã—4",
h3:"è¦‹å‡ºã—3",
h2:"è¦‹å‡ºã—2",
h1:"è¦‹å‡ºã—1",
pre:"æ•´å½¢æ¸ˆã¿",
address:"ä½æ‰€",
div:"divè¦ç´ ",
paragraph:"æ®µè½",
block:"æ›¸å¼",
fontdefault:"ãƒ•ã‚©ãƒ³ãƒˆ",
"font_size":"ãƒ•ã‚©ãƒ³ãƒˆã®å¤§ãã•",
"style_select":"ã‚¹ã‚¿ã‚¤ãƒ«",
"anchor_delta_height":"",
"anchor_delta_width":"",
"charmap_delta_height":"",
"charmap_delta_width":"",
"colorpicker_delta_height":"",
"colorpicker_delta_width":"",
"link_delta_height":"",
"link_delta_width":"",
"image_delta_height":"",
"image_delta_width":"",
"more_colors":"ãã®ä»–ã®è‰²...",
"toolbar_focus":"ãƒ„ãƒ¼ãƒ«ãƒœã‚¿ãƒ³ã¸ç§»å‹• - Alt Q, ã‚¨ãƒ‡ã‚£ã‚¿ã«ç§»å‹• - Alt-Z, è¦ç´ ã®ãƒ‘ã‚¹ã¸ç§»å‹• - Alt-X",
newdocument:"æœ¬å½“ã«ã™ã¹ã¦ã®å†…å®¹ã‚’æ¶ˆåŽ»ã—ã¦ã‚ˆã„ã§ã™ã‹?",
path:"ãƒ‘ã‚¹",
"clipboard_msg":"Mozilla ã¨ Firefox ã§ã¯ã‚³ãƒ”ãƒ¼/åˆ‡ã‚Šå–ã‚Š/è²¼ã‚Šä»˜ã‘ã¯ã§ãã¾ã›ã‚“ã€‚\nã“ã®å•é¡Œã®è©³ç´°ã‚’çŸ¥ã‚ŠãŸã„ã§ã™ã‹?",
"blockquote_desc":"å¼•ç”¨ãƒ–ãƒ­ãƒƒã‚¯",
"help_desc":"ãƒ˜ãƒ«ãƒ—",
"newdocument_desc":"æ–°è¦ãƒ‰ã‚­ãƒ¥ãƒ¡ãƒ³ãƒˆ",
"image_props_desc":"ç”»åƒã®å±žæ€§",
"paste_desc":"è²¼ã‚Šä»˜ã‘ (Ctrl+V)",
"copy_desc":"ã‚³ãƒ”ãƒ¼ (Ctrl+C)",
"cut_desc":"åˆ‡ã‚Šå–ã‚Š (Ctrl+X)",
"anchor_desc":"ã‚¢ãƒ³ã‚«ãƒ¼ã®æŒ¿å…¥/ç·¨é›†",
"visualaid_desc":"ã‚¬ã‚¤ãƒ‰ãƒ©ã‚¤ãƒ³ã¨éžè¡¨ç¤ºè¦ç´ ã®è¡¨ç¤ºã‚’åˆ‡æ›¿",
"charmap_desc":"ç‰¹æ®Šæ–‡å­—",
"backcolor_desc":"èƒŒæ™¯ã®è‰²",
"forecolor_desc":"æ–‡å­—ã®è‰²",
"custom1_desc":"èª¬æ˜Žæ–‡ã‚’å…¥åŠ›ã—ã¦ãã ã•ã„ã€‚",
"removeformat_desc":"æ›¸å¼ã®è§£é™¤",
"hr_desc":"æ°´å¹³ç·šã®æŒ¿å…¥",
"sup_desc":"ä¸Šä»˜ãæ–‡å­—",
"sub_desc":"ä¸‹ä»˜ãæ–‡å­—",
"code_desc":"HTMLã‚½ãƒ¼ã‚¹ã‚’ç·¨é›†",
"cleanup_desc":"ã‚³ãƒ¼ãƒ‰æ•´å½¢",
"image_desc":"ç”»åƒã®æŒ¿å…¥/ç·¨é›†",
"unlink_desc":"ãƒªãƒ³ã‚¯ã®è§£é™¤",
"link_desc":"ãƒªãƒ³ã‚¯ã®æŒ¿å…¥/ç·¨é›†",
"redo_desc":"ã‚„ã‚Šç›´ã— (Ctrl+Y)",
"undo_desc":"å…ƒã«æˆ»ã™ (Ctrl+Z)",
"indent_desc":"å­—ä¸‹ã’ã‚’å¢—ã‚„ã™",
"outdent_desc":"å­—ä¸‹ã’ã‚’æ¸›ã‚‰ã™",
"numlist_desc":"ç•ªå·ä»˜ããƒªã‚¹ãƒˆ",
"bullist_desc":"ç•ªå·ãªã—ãƒªã‚¹ãƒˆ",
"justifyfull_desc":"ä¸¡ç«¯æƒãˆ",
"justifyright_desc":"å³æƒãˆ",
"justifycenter_desc":"ä¸­å¤®æƒãˆ",
"justifyleft_desc":"å·¦æƒãˆ",
"striketrough_desc":"å–ã‚Šæ¶ˆã—ç·š",
"help_shortcut":"ALT-F10 ã§ãƒ„ãƒ¼ãƒ«ãƒãƒ¼ã€ALT-0 ã§ãƒ˜ãƒ«ãƒ—",
"rich_text_area":"ãƒªãƒƒãƒãƒ†ã‚­ã‚¹ãƒˆã‚¨ãƒªã‚¢",
"shortcuts_desc":"ã‚¢ã‚¯ã‚»ã‚·ãƒ“ãƒªãƒ†ã‚£ã®ãƒ˜ãƒ«ãƒ—",
toolbar:"ãƒ„ãƒ¼ãƒ«ãƒãƒ¼"});
