tinyMCE.addI18n('ja.umbraco_dlg', {"link_list":"ãƒªãƒ³ã‚¯ã®ä¸€è¦§",
"link_is_external":"å…¥åŠ›ã—ãŸURLã¯å¤–éƒ¨ã®ãƒªãƒ³ã‚¯ã®ã‚ˆã†ã§ã™ã€‚ãƒªãƒ³ã‚¯ã« http:// ã‚’è¿½åŠ ã—ã¾ã™ã‹?",
"link_is_email":"å…¥åŠ›ã—ãŸURLã¯é›»å­ãƒ¡ãƒ¼ãƒ«ã‚¢ãƒ‰ãƒ¬ã‚¹ã®ã‚ˆã†ã§ã™ã€‚ãƒªãƒ³ã‚¯ã« mailto: ã‚’è¿½åŠ ã—ã¾ã™ã‹?",
"link_titlefield":"ã‚¿ã‚¤ãƒˆãƒ«",
"link_target_blank":"æ–°ã—ã„ã‚¦ã‚¤ãƒ³ãƒ‰ã‚¦ã§é–‹ã",
"link_target_same":"åŒã˜ã‚¦ã‚¤ãƒ³ãƒ‰ã‚¦ã§é–‹ã",
"link_target":"ã‚¿ãƒ¼ã‚²ãƒƒãƒˆ",
"link_url":"ãƒªãƒ³ã‚¯ã®URL",
"link_title":"ãƒªãƒ³ã‚¯ã®æŒ¿å…¥ã‚„ç·¨é›†",
"image_align_right":"å³æƒãˆ",
"image_align_left":"å·¦æƒãˆ",
"image_align_textbottom":"ãƒ†ã‚­ã‚¹ãƒˆã®ä¸‹ç«¯æƒãˆ",
"image_align_texttop":"ãƒ†ã‚­ã‚¹ãƒˆã®ä¸Šç«¯æƒãˆ",
"image_align_bottom":"ä¸‹æƒãˆ",
"image_align_middle":"ä¸­å¤®æƒãˆ",
"image_align_top":"ä¸Šæƒãˆ",
"image_align_baseline":"ãƒ™ãƒ¼ã‚¹ãƒ©ã‚¤ãƒ³æƒãˆ",
"image_align":"é…ç½®",
"image_hspace":"å·¦å³ã®ä½™ç™½",
"image_vspace":"ä¸Šä¸‹ã®ä½™ç™½",
"image_dimensions":"å¯¸æ³•",
"image_alt":"ç”»åƒã®èª¬æ˜Ž",
"image_list":"ç”»åƒã®ä¸€è¦§",
"image_border":"æž ç·š",
"image_src":"ç”»åƒã®URL",
"image_title":"ç”»åƒã®æŒ¿å…¥/ç·¨é›†",
"charmap_title":"ç‰¹æ®Šæ–‡å­—",
"charmap_usage":"å·¦å³ã®ã‚«ãƒ¼ã‚½ãƒ«ã‚­ãƒ¼ã‚’ä½¿ç”¨ã—ã¦ç§»å‹•ã—ã¦ãã ã•ã„ã€‚",
"colorpicker_name":"åå‰:",
"colorpicker_color":"è‰²:",
"colorpicker_named_title":"å®šç¾©æ¸ˆã¿ã®è‰²",
"colorpicker_named_tab":"å®šç¾©æ¸ˆã¿",
"colorpicker_palette_title":"ãƒ‘ãƒ¬ãƒƒãƒˆã®è‰²",
"colorpicker_palette_tab":"ãƒ‘ãƒ¬ãƒƒãƒˆ",
"colorpicker_picker_title":"è‰²é¸æŠž",
"colorpicker_picker_tab":"é¸æŠž",
"colorpicker_title":"è‰²ã‚’é¸æŠž",
"code_wordwrap":"è¡Œã®æŠ˜ã‚Šè¿”ã—",
"code_title":"HTMLã‚½ãƒ¼ã‚¹ã‚¨ãƒ‡ã‚£ã‚¿",
"anchor_name":"ã‚¢ãƒ³ã‚«ãƒ¼ã®åå‰",
"anchor_title":"ã‚¢ãƒ³ã‚«ãƒ¼ã®æŒ¿å…¥/ç·¨é›†",
"about_loaded":"èª­ã¿è¾¼ã¿æ¸ˆã¿ã®ãƒ—ãƒ©ã‚°ã‚¤ãƒ³",
"about_version":"ãƒãƒ¼ã‚¸ãƒ§ãƒ³",
"about_author":"ä½œæˆè€…",
"about_plugin":"ãƒ—ãƒ©ã‚°ã‚¤ãƒ³",
"about_plugins":"ãƒ—ãƒ©ã‚°ã‚¤ãƒ³",
"about_license":"ãƒ©ã‚¤ã‚»ãƒ³ã‚¹",
"about_help":"ãƒ˜ãƒ«ãƒ—",
"about_general":"TinyMCEã«ã¤ã„ã¦",
"about_title":"TinyMCEã«ã¤ã„ã¦",
"anchor_invalid":"æœ‰åŠ¹ãªã‚¢ãƒ³ã‚«ãƒ¼ã®åå‰ã‚’æŒ‡å®šã—ã¦ãã ã•ã„ã€‚",
"accessibility_help":"ã‚¢ã‚¯ã‚»ã‚·ãƒ“ãƒªãƒ†ã‚£ã®ãƒ˜ãƒ«ãƒ—",
"accessibility_usage_title":"å…¨èˆ¬çš„ãªä½¿ã„æ–¹",
"invalid_color_value":"ç„¡åŠ¹ãªå€¤",
"":""});

