tinyMCE.addI18n('ru.umbraco_dlg',{
about_title:"ÐžÐ¿Ð¸ÑÐ°Ð½Ð¸Ðµ TinyMCE",
about_general:"ÐžÐ¿Ð¸ÑÐ°Ð½Ð¸Ðµ",
about_help:"ÐŸÐ¾Ð¼Ð¾Ñ‰ÑŒ",
about_license:"Ð›Ð¸Ñ†ÐµÐ½Ð·Ð¸Ñ",
about_plugins:"Ð”Ð¾Ð¿Ð¾Ð»Ð½Ð¸Ñ‚ÐµÐ»ÑŒÐ½Ñ‹Ðµ Ð¼Ð¾Ð´ÑƒÐ»Ð¸",
about_plugin:"ÐœÐ¾Ð´ÑƒÐ»ÑŒ",
about_author:"ÐÐ²Ñ‚Ð¾Ñ€",
about_version:"Ð’ÐµÑ€ÑÐ¸Ñ",
about_loaded:"ÐŸÐ¾Ð´ÐºÐ»ÑŽÑ‡ÐµÐ½Ð½Ñ‹Ðµ Ð¼Ð¾Ð´ÑƒÐ»Ð¸",
accessibility_help:"Ð¡Ð¿Ñ€Ð°Ð²ÐºÐ° Ð¿Ð¾ Ð´Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð¾ÑÑ‚Ð¸",
accessibility_usage_title:"ÐžÐ±Ñ‰ÐµÐ´Ð¾ÑÑ‚ÑƒÐ¿Ð½Ð¾Ðµ Ð¿Ñ€Ð¸Ð¼ÐµÐ½ÐµÐ½Ð¸Ðµ",
anchor_title:"ÐŸÐ°Ñ€Ð°Ð¼ÐµÑ‚Ñ€Ñ‹ ÑÐºÐ¾Ñ€Ñ",
anchor_name:"Ð˜Ð¼Ñ ÑÐºÐ¾Ñ€Ñ",
anchor_invalid:"Ð£ÐºÐ°Ð¶Ð¸Ñ‚Ðµ ÐºÐ¾Ñ€Ñ€ÐµÐºÑ‚Ð½Ð¾Ðµ Ð½Ð°Ð·Ð²Ð°Ð½Ð¸Ðµ ÑÐºÐ¾Ñ€Ñ.",
code_title:"Ð ÐµÐ´Ð°ÐºÑ‚Ð¾Ñ€ HTML ÐºÐ¾Ð´Ð°",
code_wordwrap:"ÐŸÐµÑ€ÐµÐ½Ð¾Ñ ÑÑ‚Ñ€Ð¾Ðº",
colorpicker_title:"Ð¦Ð²ÐµÑ‚Ð°",
colorpicker_picker_tab:"Ð¡Ð¿ÐºÑ‚Ñ€",
colorpicker_picker_title:"Ð¦Ð²ÐµÑ‚Ð°",
colorpicker_palette_tab:"ÐŸÐ°Ð»Ð¸Ñ‚Ñ€Ð°",
colorpicker_palette_title:"Ð¦Ð²ÐµÑ‚Ð°",
colorpicker_named_tab:"ÐÐ°Ð·Ð²Ð°Ð½Ð¸Ñ",
colorpicker_named_title:"Ð¦Ð²ÐµÑ‚Ð°",
colorpicker_color:"ÐšÐ¾Ð´:",
colorpicker_name:"ÐÐ°Ð·Ð²Ð°Ð½Ð¸Ðµ:",
charmap_title:"Ð’Ñ‹Ð±Ð¾Ñ€ ÑÐ¸Ð¼Ð²Ð¾Ð»Ð°",
charmap_usage:"Ð˜ÑÐ¿Ð¾Ð»ÑŒÐ·ÑƒÐ¹Ñ‚Ðµ ÑÑ‚Ñ€ÐµÐ»ÐºÐ¸ Ð²Ð¿Ñ€Ð°Ð²Ð¾ Ð¸ Ð²Ð»ÐµÐ²Ð¾ Ð´Ð»Ñ Ð½Ð°Ð²Ð¸Ð³Ð°Ñ†Ð¸Ð¸.",
image_title:"ÐŸÐ°Ñ€Ð°Ð¼ÐµÑ‚Ñ€Ñ‹ Ð¸Ð·Ð¾Ð±Ñ€Ð°Ð¶ÐµÐ½Ð¸Ñ",
image_src:"ÐÐ´Ñ€ÐµÑ",
image_alt:"ÐžÐ¿Ð¸ÑÐ°Ð½Ð¸Ðµ",
image_list:"Ð¡Ð¿Ð¸ÑÐ¾Ðº ÐºÐ°Ñ€Ñ‚Ð¸Ð½Ð¾Ðº",
image_border:"Ð“Ñ€Ð°Ð½Ð¸Ñ†Ð°",
image_dimensions:"Ð Ð°Ð·Ð¼ÐµÑ€",
image_vspace:"Ð’ÐµÑ€Ñ‚. Ð¾Ñ‚ÑÑ‚ÑƒÐ¿",
image_hspace:"Ð“Ð¾Ñ€Ð¸Ð·. Ð¾Ñ‚ÑÑ‚ÑƒÐ¿",
image_align:"Ð’Ñ‹Ñ€Ð°Ð²Ð½Ð¸Ð²Ð°Ð½Ð¸Ðµ",
image_align_baseline:"ÐŸÐ¾ Ð±Ð°Ð·Ð¾Ð²Ð¾Ð¹ Ð»Ð¸Ð½Ð¸Ð¸",
image_align_top:"ÐŸÐ¾ Ð²ÐµÑ€Ñ…Ð½ÐµÐ¼Ñƒ ÐºÑ€Ð°ÑŽ",
image_align_middle:"ÐŸÐ¾ Ñ†ÐµÐ½Ñ‚Ñ€Ñƒ",
image_align_bottom:"ÐŸÐ¾ Ð½Ð¸Ð¶Ð½ÐµÐ¼Ñƒ ÐºÑ€Ð°ÑŽ",
image_align_texttop:"ÐŸÐ¾ Ð²ÐµÑ€Ñ…Ð½ÐµÐ¼Ñƒ ÐºÑ€Ð°ÑŽ Ñ‚ÐµÐºÑÑ‚Ð°",
image_align_textbottom:"ÐŸÐ¾ Ð½Ð¸Ð¶Ð½ÐµÐ¼Ñƒ ÐºÑ€Ð°ÑŽ Ñ‚ÐµÐºÑÑ‚Ð°",
image_align_left:"ÐŸÐ¾ Ð»ÐµÐ²Ð¾Ð¼Ñƒ ÐºÑ€Ð°ÑŽ",
image_align_right:"ÐŸÐ¾ Ð¿Ñ€Ð°Ð²Ð¾Ð¼Ñƒ ÐºÑ€Ð°ÑŽ",
invalid_color_value:"ÐÐµÐºÐ¾Ñ€Ñ€ÐµÐºÑ‚Ð½Ð¾Ðµ Ð·Ð½Ð°Ñ‡ÐµÐ½Ð¸Ðµ Ñ†Ð²ÐµÑ‚Ð°",
link_title:"ÐŸÐ°Ñ€Ð°Ð¼ÐµÑ‚Ñ€Ñ‹ ÑÑÑ‹Ð»ÐºÐ¸",
link_url:"ÐÐ´Ñ€ÐµÑ",
link_target:"Ð¦ÐµÐ»ÑŒ",
link_target_same:"ÐžÑ‚ÐºÑ€Ñ‹Ñ‚ÑŒ Ð² ÑÑ‚Ð¾Ð¼ Ð¾ÐºÐ½Ðµ",
link_target_blank:"ÐžÑ‚ÐºÑ€Ñ‹Ñ‚ÑŒ Ð² Ð½Ð¾Ð²Ð¾Ð¼ Ð¾ÐºÐ½Ðµ",
link_titlefield:"Ð—Ð°Ð³Ð¾Ð»Ð¾Ð²Ð¾Ðº",
link_is_email:"Ð’Ð²ÐµÐ´ÐµÐ½Ð½Ñ‹Ð¹ Ð°Ð´Ñ€ÐµÑ Ð½Ð°Ð¿Ð¾Ð¼Ð¸Ð½Ð°ÐµÑ‚ ÑÐ»ÐµÐºÑ‚Ñ€Ð¾Ð½Ð½ÑƒÑŽ Ð¿Ð¾Ñ‡Ñ‚Ñƒ, Ð´Ð¾Ð±Ð°Ð²Ð¸Ñ‚ÑŒ mailto: Ð¿Ñ€ÐµÑ„Ð¸ÐºÑ?",
link_is_external:"Ð’Ð²ÐµÐ´ÐµÐ½Ð½Ñ‹Ð¹ Ð°Ð´Ñ€ÐµÑ Ð½Ð°Ð¿Ð¾Ð¼Ð¸Ð½Ð°ÐµÑ‚ Ð²Ð½ÐµÑˆÐ½ÑŽÑŽ ÑÑÑ‹Ð»ÐºÑƒ, Ð´Ð¾Ð±Ð°Ð²Ð¸Ñ‚ÑŒ http:// Ð¿Ñ€ÐµÑ„Ð¸ÐºÑ?",
link_list:"Ð¡Ð¿Ð¸ÑÐ¾Ðº ÑÑÑ‹Ð»Ð¾Ðº"
"":""});