tinyMCE.addI18n('zh.umbraco',{"underline_desc":"ä¸‹åˆ’çº¿ (Ctrl+U)",
"italic_desc":"æ–œä½“ (Ctrl+I)",
"bold_desc":"ç²—ä½“ (Ctrl+B)",
dd:"å®šä¹‰æè¿°",
dt:"å®šä¹‰æ¡ç›®",
samp:"ç¤ºä¾‹ä»£ç ",
code:"ä»£ç ",
blockquote:"å—å¼•ç”¨",
h6:"æ ‡é¢˜ 6",
h5:"æ ‡é¢˜ 5",
h4:"æ ‡é¢˜ 4",
h3:"æ ‡é¢˜ 3",
h2:"æ ‡é¢˜ 2",
h1:"æ ‡é¢˜ 1",
pre:"é¢„æ ¼å¼åŒ–",
address:"åœ°å€",
div:"DIV",
paragraph:"æ®µè½",
block:"æ ¼å¼åŒ–",
fontdefault:"å­—ä½“",
"font_size":"å­—å·",
"style_select":"æ ·å¼",
"anchor_delta_height":"",
"anchor_delta_width":"",
"charmap_delta_height":"",
"charmap_delta_width":"",
"colorpicker_delta_height":"",
"colorpicker_delta_width":"",
"link_delta_height":"",
"link_delta_width":"",
"image_delta_height":"",
"image_delta_width":"",
"more_colors":"æ›´å¤šé¢œè‰²â€¦",
"toolbar_focus":"è·³è½¬è‡³å·¥å…·æŒ‰é’® - Alt+Q, è·³è½¬è‡³ç¼–è¾‘å™¨ - Alt+Z, è·³è½¬è‡³å…ƒç´ è·¯å¾„ - Alt+X",
newdocument:"æ‚¨ç¡®å®šæ¸…é™¤æ‰€æœ‰å†…å®¹å—ï¼Ÿ",
path:"è·¯å¾„",
"clipboard_msg":"å¤åˆ¶/å‰ªåˆ‡/ç²˜è´´åŠŸèƒ½åœ¨Mozillaå’ŒFirefoxä¸­ä¸å¯ç”¨ï¼Œ\næ‚¨æƒ³äº†è§£æœ‰å…³è¯¥é—®é¢˜çš„æ›´å¤šä¿¡æ¯å—ï¼Ÿ",
"blockquote_desc":"å—å¼•ç”¨",
"help_desc":"å¸®åŠ©",
"newdocument_desc":"æ–°å»ºæ–‡æ¡£",
"image_props_desc":"å›¾ç‰‡å±žæ€§",
"paste_desc":"ç²˜è´´ (Ctrl+V)",
"copy_desc":"å¤åˆ¶ (Ctrl+C)",
"cut_desc":"å‰ªåˆ‡ (Ctrl+X)",
"anchor_desc":"æ’å…¥/ç¼–è¾‘é”šç‚¹",
"visualaid_desc":"æ˜¾ç¤º/éšè—å‚è€ƒçº¿å’Œä¸å¯è§å…ƒç´ ",
"charmap_desc":"æ’å…¥ç‰¹æ®Šå­—ç¬¦",
"backcolor_desc":"è®¾ç½®èƒŒæ™¯è‰²",
"forecolor_desc":"æ–‡å­—é¢œè‰²",
"custom1_desc":"è‡ªå®šä¹‰æè¿°",
"removeformat_desc":"æ¸…é™¤æ ¼å¼",
"hr_desc":"æ’å…¥æ°´å¹³çº¿",
"sup_desc":"ä¸Šæ ‡",
"sub_desc":"ä¸‹æ ‡",
"code_desc":"ç¼–è¾‘ä»£ç ",
"cleanup_desc":"å‡€åŒ–ä»£ç ",
"image_desc":"æ’å…¥/ç¼–è¾‘å›¾ç‰‡",
"unlink_desc":"å–æ¶ˆé“¾æŽ¥",
"link_desc":"æ’å…¥/ç¼–è¾‘é“¾æŽ¥",
"redo_desc":"æ’¤æ¶ˆ (Ctrl+Y)",
"undo_desc":"æ¢å¤ (Ctrl+Z)",
"indent_desc":"å¢žåŠ ç¼©è¿›",
"outdent_desc":"å‡å°‘ç¼©è¿›",
"numlist_desc":"æ’å…¥/ç§»é™¤ç¼–å·åˆ—è¡¨",
"bullist_desc":"æ’å…¥/ç§»é™¤éžç¼–å·åˆ—è¡¨",
"justifyfull_desc":"ä¸¤ç«¯å¯¹é½",
"justifyright_desc":"å³å¯¹é½",
"justifycenter_desc":"å±…ä¸­",
"justifyleft_desc":"å·¦å¯¹é½",
"striketrough_desc":"åˆ é™¤çº¿",
"help_shortcut":"æŒ‰ ALT+F10 è°ƒç”¨å·¥å…·æ . æŒ‰ ALT+0 å¯»æ±‚å¸®åŠ©",
"rich_text_area":"å¯Œæ–‡æœ¬ç¼–è¾‘åŒº",
"shortcuts_desc":"å°æç¤º",
toolbar:"å·¥å…·æ "});