tinyMCE.addI18n('zh.umbraco_dlg', {"link_list":"é“¾æŽ¥åˆ—è¡¨",
"link_is_external":"æ‚¨è¾“å…¥çš„å¥½åƒæ˜¯å¤–éƒ¨é“¾æŽ¥ï¼Œæ˜¯å¦éœ€è¦åœ¨å‰é¢æ·»åŠ  http://ï¼Ÿ",
"link_is_email":"æ‚¨è¾“å…¥çš„å¥½åƒæ˜¯é‚®ç®±åœ°å€ï¼Œæ˜¯å¦éœ€è¦åœ¨å‰é¢æ·»åŠ mailto:ï¼Ÿ",
"link_titlefield":"æ ‡é¢˜",
"link_target_blank":"åœ¨æ–°çª—å£ä¸­æ‰“å¼€é“¾æŽ¥",
"link_target_same":"åœ¨è¯¥çª—å£æ‰“å¼€é“¾æŽ¥",
"link_target":"ç›®æ ‡",
"link_url":"é“¾æŽ¥URL",
"link_title":"æ’å…¥/ç¼–è¾‘é“¾æŽ¥",
"image_align_right":"å³å¯¹é½",
"image_align_left":"å·¦å¯¹é½",
"image_align_textbottom":"å¯¹é½æ–‡å­—åº•éƒ¨",
"image_align_texttop":"å¯¹é½æ–‡å­—é¡¶éƒ¨",
"image_align_bottom":"å¯¹é½åº•éƒ¨",
"image_align_middle":"å¯¹é½ä¸­é—´",
"image_align_top":"å¯¹é½é¡¶éƒ¨",
"image_align_baseline":"åŸºçº¿å¯¹é½",
"image_align":"å¯¹é½",
"image_hspace":"æ°´å¹³é—´è·",
"image_vspace":"åž‚ç›´é—´è·",
"image_dimensions":"çº¦æŸæ¯”ä¾‹",
"image_alt":"å›¾ç‰‡æè¿°",
"image_list":"å›¾ç‰‡åˆ—è¡¨",
"image_border":"è¾¹æ¡†",
"image_src":"å›¾ç‰‡URL",
"image_title":"æ’å…¥/ç¼–è¾‘å›¾ç‰‡",
"charmap_title":"æ’å…¥å­—ç¬¦",
 "charmap_usage":"ä½¿ç”¨å·¦å³æ–¹å‘é”®é€‰æ‹©",
"colorpicker_name":"åç§°ï¼š",
"colorpicker_color":"é¢œè‰²ï¼š",
"colorpicker_named_title":"å‘½åçš„é¢œè‰²",
"colorpicker_named_tab":"å‘½åçš„",
"colorpicker_palette_title":"è°ƒè‰²æ¿é¢œè‰²",
"colorpicker_palette_tab":"è°ƒè‰²æ¿",
"colorpicker_picker_title":"é¢œè‰²æ‹¾å–å™¨",
"colorpicker_picker_tab":"æ‹¾å–å™¨",
"colorpicker_title":"é€‰æ‹©ä¸€ç§é¢œè‰²",
"code_wordwrap":"è‡ªåŠ¨æ¢è¡Œ",
"code_title":"æŸ¥çœ‹æºç ",
"anchor_name":"åç§°",
"anchor_title":"æ’å…¥/ç¼–è¾‘é”šç‚¹",
"about_loaded":"è£…è½½çš„æ’ä»¶",
"about_version":"ç‰ˆæœ¬",
"about_author":"ä½œè€…",
"about_plugin":"æ’ä»¶",
"about_plugins":"æ’ä»¶é›†",
"about_license":"æŽˆæƒ",
"about_help":"å¸®åŠ©",
"about_general":"å…³äºŽ",
"about_title":"å…³äºŽTinyMCE",
"anchor_invalid":"è¯·è¾“å…¥æœ‰æ•ˆçš„é”šç‚¹å",
"accessibility_help":"å°æç¤º",
"accessibility_usage_title":"ä¸€èˆ¬ç”¨æ³•",
"invalid_color_value":"é”™è¯¯çš„é¢œè‰²å€¼",
"":""});